Repository Azure/azureml-assets, pull requests merged in 2024-09, with the labels that each got.

#3338 Added more automl environments
  assets/training/automl/environments/ai-ml-automl-dnn-gpu/README.md
  assets/training/automl/environments/ai-ml-automl-dnn-gpu/asset.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-gpu/context/Dockerfile
  assets/training/automl/environments/ai-ml-automl-dnn-gpu/environment.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-gpu/spec.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-gpu/tests/automl_sample_test.py
  assets/training/automl/environments/ai-ml-automl-dnn-gpu/tests/requirements.txt
  assets/training/automl/environments/ai-ml-automl-dnn-gpu/tests/src/main.py
  assets/training/automl/environments/ai-ml-automl-dnn/README.md
  assets/training/automl/environments/ai-ml-automl-dnn/asset.yaml
  assets/training/automl/environments/ai-ml-automl-dnn/context/Dockerfile
  assets/training/automl/environments/ai-ml-automl-dnn/environment.yaml
  assets/training/automl/environments/ai-ml-automl-dnn/spec.yaml
  assets/training/automl/environments/ai-ml-automl-dnn/tests/automl_sample_test.py
  assets/training/automl/environments/ai-ml-automl-dnn/tests/requirements.txt
  assets/training/automl/environments/ai-ml-automl-dnn/tests/src/main.py
  assets/training/automl/environments/ai-ml-automl-gpu/README.md
  assets/training/automl/environments/ai-ml-automl-gpu/asset.yaml
  assets/training/automl/environments/ai-ml-automl-gpu/context/Dockerfile
  assets/training/automl/environments/ai-ml-automl-gpu/environment.yaml
  assets/training/automl/environments/ai-ml-automl-gpu/spec.yaml
  assets/training/automl/environments/ai-ml-automl-gpu/tests/automl_sample_test.py
  assets/training/automl/environments/ai-ml-automl-gpu/tests/requirements.txt
  assets/training/automl/environments/ai-ml-automl-gpu/tests/src/main.py
Labels: safe to publish

#3341 Added automl forecasting, text and vision envirnments
  assets/training/automl/environments/ai-ml-automl-dnn-forecasting-gpu/README.md
  assets/training/automl/environments/ai-ml-automl-dnn-forecasting-gpu/asset.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-forecasting-gpu/context/Dockerfile
  assets/training/automl/environments/ai-ml-automl-dnn-forecasting-gpu/environment.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-forecasting-gpu/spec.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-forecasting-gpu/tests/automl_sample_test.py
  assets/training/automl/environments/ai-ml-automl-dnn-forecasting-gpu/tests/requirements.txt
  assets/training/automl/environments/ai-ml-automl-dnn-forecasting-gpu/tests/src/main.py
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu-ptca/README.md
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu-ptca/asset.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu-ptca/context/Dockerfile
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu-ptca/environment.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu-ptca/spec.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu-ptca/tests/automl_sample_test.py
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu-ptca/tests/requirements.txt
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu-ptca/tests/src/main.py
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu/README.md
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu/asset.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu/context/Dockerfile
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu/environment.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu/spec.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu/tests/automl_sample_test.py
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu/tests/requirements.txt
  assets/training/automl/environments/ai-ml-automl-dnn-text-gpu/tests/src/main.py
  assets/training/automl/environments/ai-ml-automl-dnn-vision-gpu/README.md
  assets/training/automl/environments/ai-ml-automl-dnn-vision-gpu/asset.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-vision-gpu/context/Dockerfile
  assets/training/automl/environments/ai-ml-automl-dnn-vision-gpu/environment.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-vision-gpu/spec.yaml
  assets/training/automl/environments/ai-ml-automl-dnn-vision-gpu/tests/automl_sample_test.py
  assets/training/automl/environments/ai-ml-automl-dnn-vision-gpu/tests/requirements.txt
  assets/training/automl/environments/ai-ml-automl-dnn-vision-gpu/tests/src/main.py
Labels: safe to publish

#3377 Validation for vision results
  scripts/azureml-assets/CHANGELOG.md
  scripts/azureml-assets/azureml/assets/config/evaluationresult/tag_values_shared.yaml
  scripts/azureml-assets/azureml/assets/config/evaluationresult/tag_values_vision.yaml
  scripts/azureml-assets/azureml/assets/validate_assets.py
  scripts/azureml-assets/setup.py
  test/resources/validate/evaluationresult/vision_correct/asset.yaml
  test/resources/validate/evaluationresult/vision_correct/spec.yaml
  test/resources/validate/evaluationresult/vision_incorrect/asset.yaml
  test/resources/validate/evaluationresult/vision_incorrect/spec.yaml
  test/test_validate_assets.py
Labels: safe to publish

#3342 Assets for SD on COCO
  assets/evaluation_results/mscoco__stabilityai-stable-diffusion-2-1__image_generation/asset.yaml
  assets/evaluation_results/mscoco__stabilityai-stable-diffusion-2-1__image_generation/spec.yaml
Labels: safe to publish

#3403 Add new UI eval flow
  assets/promptflow/models/rai-eval-ui-dag-flow/asset.yaml
  assets/promptflow/models/rai-eval-ui-dag-flow/description.md
  assets/promptflow/models/rai-eval-ui-dag-flow/model.yaml
  assets/promptflow/models/rai-eval-ui-dag-flow/spec.yaml
  scripts/promptflow-ci/test-configs/rai-eval-ui-dag-flow/test_config.json
Labels: safe to test, safe to publish

#3411 Add new UI eval flow
  assets/promptflow/.cspell.json
  assets/promptflow/models/rai-eval-ui-dag-flow/asset.yaml
  assets/promptflow/models/rai-eval-ui-dag-flow/description.md
  assets/promptflow/models/rai-eval-ui-dag-flow/model.yaml
  assets/promptflow/models/rai-eval-ui-dag-flow/spec.yaml
  scripts/promptflow-ci/test-configs/rai-eval-ui-dag-flow/test_config.json
Labels: safe to test, safe to publish

#3424 Add math based evaluators
  assets/promptflow/evaluators/models/bleu-score-evaluator/asset.yaml
  assets/promptflow/evaluators/models/bleu-score-evaluator/description.md
  assets/promptflow/evaluators/models/bleu-score-evaluator/model.yaml
  assets/promptflow/evaluators/models/bleu-score-evaluator/spec.yaml
  assets/promptflow/evaluators/models/gleu-score-evaluator/asset.yaml
  assets/promptflow/evaluators/models/gleu-score-evaluator/description.md
  assets/promptflow/evaluators/models/gleu-score-evaluator/model.yaml
  assets/promptflow/evaluators/models/gleu-score-evaluator/spec.yaml
  assets/promptflow/evaluators/models/meteor-score-evaluator/asset.yaml
  assets/promptflow/evaluators/models/meteor-score-evaluator/description.md
  assets/promptflow/evaluators/models/meteor-score-evaluator/model.yaml
  assets/promptflow/evaluators/models/meteor-score-evaluator/spec.yaml
  assets/promptflow/evaluators/models/rouge-score-evaluator/asset.yaml
  assets/promptflow/evaluators/models/rouge-score-evaluator/description.md
  assets/promptflow/evaluators/models/rouge-score-evaluator/model.yaml
  assets/promptflow/evaluators/models/rouge-score-evaluator/spec.yaml
Labels: safe to test, safe to publish

#3431 Allow Azure-AI prefix for models
  scripts/azureml-assets/CHANGELOG.md
  scripts/azureml-assets/azureml/assets/validate_assets.py
  scripts/azureml-assets/setup.py
  test/resources/validate/azure-ai-model-bad/asset.yaml
  test/resources/validate/azure-ai-model-bad/model.yaml
  test/resources/validate/azure-ai-model-bad/spec.yaml
  test/resources/validate/azure-ai-model/asset.yaml
  test/resources/validate/azure-ai-model/description.md
  test/resources/validate/azure-ai-model/model.yaml
  test/resources/validate/azure-ai-model/spec.yaml
  test/test_validate_assets.py
Labels: safe to publish

#3434 Moved ALLaM-2-7b-instruct spec from azureml-asset
  assets/models/system/ALLaM-2-7b-instruct/LICENSE.md
  assets/models/system/ALLaM-2-7b-instruct/asset.yaml
  assets/models/system/ALLaM-2-7b-instruct/description.md
  assets/models/system/ALLaM-2-7b-instruct/model.yaml
  assets/models/system/ALLaM-2-7b-instruct/spec.yaml
Labels: safe to publish

#3441 Update model versions
  assets/models/system/phi-3-vision-128k-instruct/spec.yaml
  assets/models/system/snowflake-artic-instruct/spec.yaml
  assets/models/system/stabilityai-stable-diffusion-xl-refiner-1-0/spec.yaml
Labels: safe to test
