Repository Azure/azureml-assets, pull requests merged in 2025-02, with the labels that each got.

#3826 update eci asset to v3
  assets/promptflow/evaluators/models/eci-evaluator/model.yaml
Labels: safe to test

#3827 v3 eci
  assets/promptflow/evaluators/models/eci-evaluator/spec.yaml
Labels: safe to test, safe to publish

#3803 Updated aurora/mattersim/tamgen metadata
  assets/models/system/TamGen/spec.yaml
  assets/models/system/aurora/spec.yaml
  assets/models/system/mattersim/spec.yaml
Labels: safe to test

#3791 feat: added learning-rate tags to some models for finetuning
  assets/models/system/phi-3-medium-128k-instruct/spec.yaml
  assets/models/system/phi-3-medium-4k-instruct/spec.yaml
  assets/models/system/phi-3-mini-128k-instruct/spec.yaml
  assets/models/system/phi-3-mini-4k-instruct/spec.yaml
  assets/models/system/phi-3-small-128k-instruct/spec.yaml
  assets/models/system/phi-3.5-mini-128k-instruct/spec.yaml
  assets/models/system/phi-3.5-moe-128k-instruct/spec.yaml
Labels: safe to test

#3888 Model Card MedImageParse3D
  assets/models/system/MedImageParse3D/asset.yaml
  assets/models/system/MedImageParse3D/description.md
  assets/models/system/MedImageParse3D/evaluation.md
  assets/models/system/MedImageParse3D/model.yaml
  assets/models/system/MedImageParse3D/notes.md
  assets/models/system/MedImageParse3D/spec.yaml
Labels: safe to publish
