Repository Azure/azureml-assets, pull requests merged in 2025-05, with the labels that each got.

#4137 Add support for deepseek-r1-distill-qwen-7b and deepseek-r1-distill-qwen-7b local model variants
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-cuda-gpu/asset.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-cuda-gpu/description.md
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-cuda-gpu/model.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-cuda-gpu/spec.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-generic-cpu/asset.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-generic-cpu/description.md
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-generic-cpu/model.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-generic-cpu/spec.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-generic-gpu/asset.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-generic-gpu/description.md
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-generic-gpu/model.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B-generic-gpu/spec.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B/asset.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B/description.md
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B/model.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-1.5B/spec.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-cuda-gpu/asset.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-cuda-gpu/description.md
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-cuda-gpu/model.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-cuda-gpu/spec.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-generic-cpu/asset.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-generic-cpu/description.md
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-generic-cpu/model.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-generic-cpu/spec.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-generic-gpu/asset.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-generic-gpu/description.md
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-generic-gpu/model.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B-generic-gpu/spec.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B/asset.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B/description.md
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B/model.yaml
  assets/models/system/DeepSeek-R1-Distill-Qwen-7B/spec.yaml
Labels: safe to publish

#4169 Add case in-sensitive get and update logging
  assets/evaluation_on_cloud/environments/evaluations-built-in/context/evaluate_on_data.py
  assets/evaluation_on_cloud/environments/evaluations-built-in/context/model_target.py
Labels: safe to test

#4190 [BugFix]: Framework selector for image task fails with azure.ai impor…
  assets/training/finetune_acft_common/components/validation/asset.yaml
  assets/training/finetune_acft_common/components/validation/spec.yaml
  assets/training/finetune_acft_common/src/validation/validation.py
  assets/training/finetune_acft_image/components/finetune/mmd_od_is/asset.yaml
  assets/training/finetune_acft_image/components/finetune/mmd_od_is/spec.yaml
  assets/training/finetune_acft_image/components/framework_selector/asset.yaml
  assets/training/finetune_acft_image/components/framework_selector/spec.yaml
  assets/training/finetune_acft_image/components/model_import/diffusers_text_to_image/asset.yaml
  assets/training/finetune_acft_image/components/model_import/diffusers_text_to_image/spec.yaml
  assets/training/finetune_acft_image/components/model_import/hf_classification/asset.yaml
  assets/training/finetune_acft_image/components/model_import/hf_classification/spec.yaml
  assets/training/finetune_acft_image/components/model_import/mmd_od_is/asset.yaml
  assets/training/finetune_acft_image/components/model_import/mmd_od_is/spec.yaml
  assets/training/finetune_acft_image/components/model_import/mmt/asset.yaml
  assets/training/finetune_acft_image/components/model_import/mmt/spec.yaml
  assets/training/finetune_acft_image/components/model_output_selector/asset.yaml
  assets/training/finetune_acft_image/components/model_output_selector/spec.yaml
  assets/training/finetune_acft_image/components/pipeline_components/instance_segmentation/asset.yaml
  assets/training/finetune_acft_image/components/pipeline_components/instance_segmentation/spec.yaml
  assets/training/finetune_acft_image/environments/acpt_image_framework_selector/context/requirements.txt
  assets/training/finetune_acft_image/src/framework_selector/framework_selector.py
  assets/training/vision/components/instance_segmentation/asset.yaml
  assets/training/vision/components/instance_segmentation/spec.yaml
Labels: safe to publish

#4200 Paige model custom environments
  assets/training/model_management/environments/mlflow-model-inference/context/runit/gunicorn/run
Labels: DYNAMIC_DEP_INSTALLATION

#4192 FMI vulnerability fix
  assets/training/model_management/environments/foundation-model-inference/context/Dockerfile
Labels: V1SDK-Exception

#4210 [Update]: recover and update compute metrics for notebook runs fix
  assets/training/model_evaluation/components/compute_metrics/README.md
  assets/training/model_evaluation/components/compute_metrics/asset.yaml
  assets/training/model_evaluation/components/compute_metrics/spec.yaml
Labels: safe to publish
