Repository Azure/azureml-assets, pull requests merged in 2025-07, with the labels that each got.

#4311 add hibou-l model
  assets/models/system/hibou-l/MLmodel
  assets/models/system/hibou-l/asset.yaml
  assets/models/system/hibou-l/description.md
  assets/models/system/hibou-l/model.yaml
  assets/models/system/hibou-l/notes.md
  assets/models/system/hibou-l/spec.yaml
Labels: safe to publish, mlflow noncompliant exception

#4306 Update libudev1 lib
  assets/training/model_management/environments/mlflow-model-inference/context/Dockerfile
Labels: mlflow noncompliant exception

#4321 [Enhancement]: environment for group relative policy optimization
  assets/training/finetune_acft_hf_nlp/environments/acpt-grpo/asset.yaml
  assets/training/finetune_acft_hf_nlp/environments/acpt-grpo/context/Dockerfile
  assets/training/finetune_acft_hf_nlp/environments/acpt-grpo/context/requirements.txt
  assets/training/finetune_acft_hf_nlp/environments/acpt-grpo/environment.yaml
  assets/training/finetune_acft_hf_nlp/environments/acpt-grpo/spec.yaml
Labels: safe to publish

#4326 [Enhancement]: new group relative policy optimization pipeline
  assets/training/finetune_acft_hf_nlp/components/grpo/chat_completion/README.md
  assets/training/finetune_acft_hf_nlp/components/grpo/chat_completion/asset.yaml
  assets/training/finetune_acft_hf_nlp/components/grpo/chat_completion/spec.yaml
  assets/training/finetune_acft_hf_nlp/components/model_import/chat_completion/spec.yaml
  assets/training/finetune_acft_hf_nlp/components/pipeline_components/grpo_chat_completion/README.md
  assets/training/finetune_acft_hf_nlp/components/pipeline_components/grpo_chat_completion/asset.yaml
  assets/training/finetune_acft_hf_nlp/components/pipeline_components/grpo_chat_completion/spec.yaml
  assets/training/finetune_acft_hf_nlp/src/grpo/grpo_trainer_callbacks.py
  assets/training/finetune_acft_hf_nlp/src/grpo/grpo_trainer_rewards.py
  assets/training/finetune_acft_hf_nlp/src/grpo/reasoning_train.py
  assets/training/finetune_acft_hf_nlp/src/model_selector/model_selector.py
Labels: safe to publish

#4331 add license info for hls models
  assets/models/system/Atomica/spec.yaml
  assets/models/system/MedSAM2/spec.yaml
  assets/models/system/hibou-b/spec.yaml
  assets/models/system/hibou-l/spec.yaml
Labels: mlflow noncompliant exception

#4344 add medvae 8x4x2d model
  assets/models/system/MedVAE-8-4-2d/MLmodel
  assets/models/system/MedVAE-8-4-2d/asset.yaml
  assets/models/system/MedVAE-8-4-2d/description.md
  assets/models/system/MedVAE-8-4-2d/model.yaml
  assets/models/system/MedVAE-8-4-2d/spec.yaml
Labels: safe to publish, mlflow noncompliant exception

#4346 Update task to embeddings
  assets/models/system/Atomica/spec.yaml
  assets/models/system/hibou-b/spec.yaml
  assets/models/system/hibou-l/spec.yaml
Labels: mlflow noncompliant exception

#4350 Update requirements.txt
  assets/training/model_management/environments/model-management/context/Dockerfile
  assets/training/model_management/environments/model-management/context/requirements.txt
Labels: V1SDK-Exception
