Repository Azure/azureml-assets, pull requests merged in 2025-03, with the labels that each got.

#3909 Revert versions to match PROD
  assets/models/system/phi-3.5-mini-128k-instruct/spec.yaml
  assets/models/system/phi-3.5-moe-128k-instruct/spec.yaml
Labels: safe to test

#3872 [Enhancement]: medimage insight environments
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_adapter_finetune/asset.yaml
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_adapter_finetune/context/Dockerfile
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_adapter_finetune/context/requirements.txt
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_adapter_finetune/environment.yaml
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_adapter_finetune/spec.yaml
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding/asset.yaml
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding/context/Dockerfile
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding/context/requirements.txt
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding/environment.yaml
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding/spec.yaml
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding_generator/asset.yaml
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding_generator/context/Dockerfile
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding_generator/context/requirements.txt
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding_generator/environment.yaml
  assets/training/finetune_acft_image/environments/acft_image_medimageinsight_embedding_generator/spec.yaml
Labels: safe to publish

#3914 Updating version of MedImageParse
  assets/models/system/medimageparse/spec.yaml
Labels: safe to test

#3928 Fix validate assets for updated task in quality evaluationresult assets
  scripts/azureml-assets/CHANGELOG.md
  scripts/azureml-assets/azureml/assets/config/evaluationresult/tag_values_text_generation.yaml
  scripts/azureml-assets/setup.py
  test/resources/validate/evaluationresult/text_generation_updated_task/asset.yaml
  test/resources/validate/evaluationresult/text_generation_updated_task/spec.yaml
  test/test_validate_assets.py
Labels: safe to publish

#3932 [Enhancement]: Components for MedImageInsight finetune
  assets/training/finetune_acft_image/components/finetune/medimage_adapter/asset.yaml
  assets/training/finetune_acft_image/components/finetune/medimage_adapter/spec.yaml
  assets/training/finetune_acft_image/components/finetune/medimage_insight/asset.yaml
  assets/training/finetune_acft_image/components/finetune/medimage_insight/spec.yaml
  assets/training/finetune_acft_image/components/model_converters/medimage_embed_adapter_merge/asset.yaml
  assets/training/finetune_acft_image/components/model_converters/medimage_embed_adapter_merge/spec.yaml
  assets/training/finetune_acft_image/components/preprocess/image_embedding/asset.yaml
  assets/training/finetune_acft_image/components/preprocess/image_embedding/spec.yaml
  assets/training/finetune_acft_image/src/medimage_insight_adapter_finetune/medimage_train.py
  assets/training/finetune_acft_image/src/medimage_insight_adapter_finetune/training.py
  assets/training/finetune_acft_image/src/medimage_insight_adapter_preprocess/medimage_datapreprocess.py
  assets/training/finetune_acft_image/src/medimage_insight_embedding_finetune/medimage_embedding_finetune.py
  assets/training/finetune_acft_image/src/model_converters/medimage_embed_adapter_merge/MLmodel
  assets/training/finetune_acft_image/src/model_converters/medimage_embed_adapter_merge/medimage_model_merge.py
  assets/training/finetune_acft_image/src/model_converters/medimage_embed_adapter_merge/medimageinsight_classification_mlflow_wrapper.py
Labels: safe to publish

#3936 [Enhancement]: MedImage Insight pipeline component
  assets/training/finetune_acft_image/components/pipeline_components/medimage_insight_ft/asset.yaml
  assets/training/finetune_acft_image/components/pipeline_components/medimage_insight_ft/spec.yaml
Labels: safe to publish

#3945 Update featurestore component to 1.1.1
  assets/featurestore/components/feature_retrieval/spec.yaml
Labels: safe to test

#3943 Model mgmt vul fix
  assets/training/model_management/environments/model-management/context/requirements.txt
Labels: V1SDK-Exception

#3957 Update spec.yaml for deprecation date information
  assets/models/system/Llama-2-7b-chat/spec.yaml
Labels: safe to test

#3953 Update spec.yaml for Llama 2 models to include deprecation date information
  assets/models/system/Llama-2-13b/spec.yaml
Labels: safe to test

#3954 Update spec.yaml to include deprecation information
  assets/models/system/Llama-2-7b/spec.yaml
Labels: safe to test

#3956 Update spec.yaml to include deprecation information
  assets/models/system/Llama-2-13b-chat/spec.yaml
Labels: safe to test

#3958 Update spec.yaml for deprecation date information
  assets/models/system/Llama-2-70b-chat/spec.yaml
Labels: safe to test

#3970 Update Dockerfile for model_management vulnerability fix
  assets/training/model_management/environments/model-management/context/Dockerfile
Labels: V1SDK-Exception

#3971 Base mlflow model inference image
  assets/training/model_management/environments/mlflow-model-inference/asset.yaml
  assets/training/model_management/environments/mlflow-model-inference/context/Dockerfile
  assets/training/model_management/environments/mlflow-model-inference/context/common/aml_logger/appinsights_recorder.py
  assets/training/model_management/environments/mlflow-model-inference/context/common/aml_logger/recorder_factory.py
  assets/training/model_management/environments/mlflow-model-inference/context/common/aml_logger/rsyslog_plugin.py
  assets/training/model_management/environments/mlflow-model-inference/context/common/aml_logger/start_logger.sh
  assets/training/model_management/environments/mlflow-model-inference/context/conda_dependencies.yaml
  assets/training/model_management/environments/mlflow-model-inference/context/configs/app
  assets/training/model_management/environments/mlflow-model-inference/context/configs/rsyslog.conf
  assets/training/model_management/environments/mlflow-model-inference/context/grant_ownership.sh
  assets/training/model_management/environments/mlflow-model-inference/context/mlflow_hf_score_cpu.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlflow_hf_score_gpu.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlflow_score_script.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/__init__.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/collector.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/collector_base.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/collector_json.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/common/__init__.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/config/__init__.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/config/config.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/context/__init__.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/context/context.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/init.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/logger/__init__.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/logger/logger.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/payload/__init__.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/payload/logdata.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/payload/payload.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/queue/__init__.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/queue/queue.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/worker/__init__.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/worker/sender.py
  assets/training/model_management/environments/mlflow-model-inference/context/mlmonitoring/worker/worker.py
  assets/training/model_management/environments/mlflow-model-inference/context/runit/gunicorn/ensure_debugging.py
  assets/training/model_management/environments/mlflow-model-inference/context/runit/gunicorn/finish
  assets/training/model_management/environments/mlflow-model-inference/context/runit/gunicorn/run
  assets/training/model_management/environments/mlflow-model-inference/context/runit/nginx/finish
  assets/training/model_management/environments/mlflow-model-inference/context/runit/nginx/run
  assets/training/model_management/environments/mlflow-model-inference/context/runit/rsyslog/finish
  assets/training/model_management/environments/mlflow-model-inference/context/runit/rsyslog/run
  assets/training/model_management/environments/mlflow-model-inference/context/utilities/start_logger.sh
  assets/training/model_management/environments/mlflow-model-inference/environment.yaml
  assets/training/model_management/environments/mlflow-model-inference/spec.yaml
Labels: safe to publish

#3992 responsibleai text and vision 0.0.21 components
  assets/responsibleai/environments/responsibleai-text/context/Dockerfile
  assets/responsibleai/environments/responsibleai-vision/context/Dockerfile
  assets/responsibleai/text/components/rai_text_insights/spec.yaml
  assets/responsibleai/text/components/src/rai_text_insights.py
  assets/responsibleai/vision/components/rai_vision_insights/spec.yaml
  assets/responsibleai/vision/components/src/rai_vision_insights.py
Labels: V1SDK-Exception

#3974 Aawal/financial reports analysis v2 supply chain trade regulations v2
  assets/models/system/financial-reports-analysis-v2/asset.yaml
  assets/models/system/financial-reports-analysis-v2/description.md
  assets/models/system/financial-reports-analysis-v2/evaluation.md
  assets/models/system/financial-reports-analysis-v2/model.yaml
  assets/models/system/financial-reports-analysis-v2/notes.md
  assets/models/system/financial-reports-analysis-v2/spec.yaml
  assets/models/system/supply-chain-trade-regulations-v2/asset.yaml
  assets/models/system/supply-chain-trade-regulations-v2/description.md
  assets/models/system/supply-chain-trade-regulations-v2/evaluation.md
  assets/models/system/supply-chain-trade-regulations-v2/model.yaml
  assets/models/system/supply-chain-trade-regulations-v2/notes.md
  assets/models/system/supply-chain-trade-regulations-v2/spec.yaml
Labels: safe to publish

#4010 Fix RAI vision image cJSON ffmpeg vulnerabilities
  assets/responsibleai/environments/responsibleai-vision/context/Dockerfile
  assets/responsibleai/vision/components/rai_vision_insights/spec.yaml
Labels: V1SDK-Exception

#3984 Update Dockerfile with python_sdk_v2_fixes
  assets/common/environments/python-sdk-v2/context/Dockerfile
Labels: V1SDK-Exception
