Repository Azure/azureml-assets, pull requests merged in 2025-06, with the labels that each got.

#4241 Phi-4 H100 Enablement
  assets/models/system/Phi-4/spec.yaml
Labels: mlflow noncompliant exception

#4251 Update spec.yaml
  assets/models/system/phi-3-medium-128k-instruct/spec.yaml
  assets/models/system/phi-3-medium-4k-instruct/spec.yaml
  assets/models/system/phi-3-mini-128k-instruct/spec.yaml
  assets/models/system/phi-3-mini-4k-instruct/spec.yaml
  assets/models/system/phi-3-small-128k-instruct/spec.yaml
  assets/models/system/phi-3-small-8k-instruct/spec.yaml
  assets/models/system/phi-3-vision-128k-instruct/spec.yaml
  assets/models/system/phi-3.5-mini-128k-instruct/spec.yaml
  assets/models/system/phi-3.5-moe-128k-instruct/spec.yaml
  assets/models/system/phi-3.5-vision-128k-instruct/spec.yaml
Labels: safe to test, mlflow noncompliant exception

#4277 Flask cors torch fix
  assets/training/model_management/environments/mlflow-model-inference/context/conda_dependencies.yaml
  assets/training/model_management/environments/model-management/context/requirements.txt
Labels: V1SDK-Exception

#4279 MIP model update version
  assets/models/system/medimageparse/spec.yaml
Labels: mlflow noncompliant exception

#4281 Python version update
  assets/models/system/Deci-DeciCoder-1b/MLmodel
  assets/models/system/Deci-DeciCoder-1b/spec.yaml
  assets/models/system/Deci-DeciLM-7B-instruct/MLmodel
  assets/models/system/Deci-DeciLM-7B-instruct/spec.yaml
  assets/models/system/Deci-DeciLM-7B/MLmodel
  assets/models/system/Deci-DeciLM-7B/spec.yaml
  assets/models/system/jean-baptiste-camembert-ner/MLmodel
  assets/models/system/jean-baptiste-camembert-ner/spec.yaml
Labels: mlflow noncompliant exception

#4289 bump atomica version as we updated conda yaml
  assets/models/system/Atomica/spec.yaml
Labels: mlflow noncompliant exception

#4297 Update version up
  assets/models/system/TamGen/spec.yaml
Labels: mlflow noncompliant exception
